name: "Coverage"

on:
  pull_request:

  push:
    branches: ["*"]

  schedule:
    - cron: "0 8 * * 1"

env:
  extensions: "json, pdo_mysql"
  cache-version: "1"
  composer-version: "v2"
  composer-install: "composer update --no-interaction --no-progress --no-suggest --prefer-dist --prefer-stable"

  DATABASE_DSN: 'mysql:host=127.0.0.1;port=3306;dbname=test'
  DATABASE_USER: 'root'
  DATABASE_PASSWORD: 'test'

jobs:
  services:
    database:
      image: mariadb:latest
      ports:
        - 3306:3306
      env:
        MYSQL_ROOT_PASSWORD: 'test'
        MYSQL_DATABASE: 'test'
      options: >-
        --health-cmd="mysqladmin ping"
        --health-interval=10s
        --health-timeout=5s
        --health-retries=3

  build:
    name: "Coverage"
    uses: contributte/.github/.github/workflows/nette-tester-coverage.yml@v1
    with:
      php: "8.2"