name: "Coverage"

on:
  pull_request:

  push:
    branches: ["*"]

  schedule:
    - cron: "0 8 * * 1"

env:
  extensions: "json, pdo_mysql"

jobs:
  tests:
    name: "Coverage"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        php: [ "8.2", "8.1", "8.0" ]
        os: [ubuntu-latest]
        #os: [ubuntu-latest, windows-latest, macOS-latest]

    services:
      database:
        image: mariadb:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: 'test'
          MYSQL_DATABASE: 'test'
        options: --health-cmd="healthcheck.sh --su-mysql --connect --innodb_initialized" --health-interval=10s --health-timeout=5s --health-retries=3


    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: "${{ env.extensions }}"

      - run: composer install --no-progress --prefer-dist

      - run: make coverage
        shell: bash
        env:
          DATABASE_DSN: 'mysql:host=127.0.0.1;port=3306;dbname=test'
          DATABASE_USER: 'root'
          DATABASE_PASSWORD: 'test'

